In [1]:
# Import all relevant libraries for data analysis and visualization

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from matplotlib.ticker import FuncFormatter

In [2]:
# Import and concatenate all CSV files from the specified directory into one DataFrame named july2025_mp
import glob
import os
mp_dir = r'C:\Users\theam\Documents\1. Academics\1. First Semester\1. ECON 199\3. Python Project\July Project\RTD Market Clearing Price'
# Find all CSV files in the directory
csv_files = glob.glob(os.path.join(mp_dir, '*.csv'))
mp_dataframes = [pd.read_csv(f) for f in csv_files]
if mp_dataframes:
    july2025_mp = pd.concat(mp_dataframes, ignore_index=True)
    display(july2025_mp)
else:
    print('No CSV files found in the specified directory.')

,RUN_TIME,MKT_TYPE,TIME_INTERVAL,REGION_NAME,RESOURCE_NAME,RESOURCE_TYPE,COMMODITY_TYPE,MARGINAL_PRICE,Unnamed: 8
0,7/1/2025,RTD,7/1/2025 12:05:00 AM,CLUZ,03STA-RI_G01,G,En,5412.20,NaN
1,7/1/2025,RTD,7/1/2025 12:05:00 AM,CMIN,14SARANG_U02,G,En,2731.00,NaN
2,7/1/2025 12:05:00 AM,RTD,7/1/2025 12:10:00 AM,CLUZ,03PAGBIL_G01,G,En,3536.43,NaN
3,7/1/2025 12:05:00 AM,RTD,7/1/2025 12:10:00 AM,CLUZ,03PAGBIL_G02,G,En,3536.43,NaN
4,7/1/2025 12:05:00 AM,RTD,7/1/2025 12:10:00 AM,CMIN,14SARANG_U02,G,En,2731.00,NaN
...,...,...,...,...,...,...,...,...,...
20708,7/31/2025 11:55:00 PM,RTD,8/1/2025,CMIN,10GNPK_U01,G,En,5400.00,NaN
20709,7/31/2025 11:55:00 PM,RTD,8/1/2025,CMIN,10GNPK_U02,G,En,5400.00,NaN
20710,7/31/2025 11:55:00 PM,RTD,8/1/2025,CMIN,10GNPK_U03,G,En,5400.00,NaN
20711,7/31/2025 11:55:00 PM,RTD,8/1/2025,CMIN,10GNPK_U04,G,En,5400.00,NaN
20712,EOF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
import zipfile
import os
import glob
import pandas as pd

# Specify the directory containing the zip files
zip_dir = r'C:\Users\theam\Documents\1. Academics\1. First Semester\1. ECON 199\3. Python Project\July Project\RTD Prices and Schedules'

# Extract all zip files in the directory and subdirectories
for root, dirs, files in os.walk(zip_dir):
    for file in files:
        if file.endswith('.zip'):
            zip_path = os.path.join(root, file)
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(zip_dir)

# After extraction, read all CSV files into DataFrames
csv_files = glob.glob(os.path.join(zip_dir, '**', '*.csv'), recursive=True)
dataframes = [pd.read_csv(f) for f in csv_files]

In [4]:
# Concatenate all dataframes into one
if dataframes:
    july2025_mw = pd.concat(dataframes, ignore_index=True)
    display(july2025_mw)
else:
    print("No CSV files were loaded.")

,RUN_TIME,MKT_TYPE,TIME_INTERVAL,REGION_NAME,RESOURCE_NAME,RESOURCE_TYPE,SCHED_MW,LMP,LOSS_FACTOR,LMP_SMP,LMP_LOSS,LMP_CONGESTION,Unnamed: 12
0,6/30/2025 11:00:00 PM,RTD,6/30/2025 11:05:00 PM,CLUZ,01ACNPC_G01,G,1.00,3398.8958,0.9793,3328.6611,70.2347,0.0,NaN
1,6/30/2025 11:00:00 PM,RTD,6/30/2025 11:05:00 PM,CLUZ,01AEC_L01,NL,-49.70,3396.8986,0.9799,3328.6611,68.2376,0.0,NaN
2,6/30/2025 11:00:00 PM,RTD,6/30/2025 11:05:00 PM,CLUZ,01AMBUK_SS,NL,0.00,3379.9225,0.9848,3328.6611,51.2614,0.0,NaN
3,6/30/2025 11:00:00 PM,RTD,6/30/2025 11:05:00 PM,CLUZ,01AMBUK_T1L1,NL,0.00,3379.9225,0.9848,3328.6611,51.2614,0.0,NaN
4,6/30/2025 11:00:00 PM,RTD,6/30/2025 11:05:00 PM,CLUZ,01AMBUK_U01,G,37.50,3377.9253,0.9854,3328.6611,49.2642,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9963043,7/31/2025 10:55:00 PM,RTD,7/31/2025 11:00:00 PM,CMIN,14TACSUR_L02,NL,-29.15,15465.4987,0.8239,12741.3896,2724.1091,0.0,NaN
9963044,7/31/2025 10:55:00 PM,RTD,7/31/2025 11:00:00 PM,CMIN,14TACUR_SS,NL,0.00,15459.1280,0.8242,12741.3896,2717.7384,0.0,NaN
9963045,7/31/2025 10:55:00 PM,RTD,7/31/2025 11:00:00 PM,CMIN,14TIN_T1L1,NL,-19.33,15075.6122,0.8451,12741.3896,2334.2226,0.0,NaN
9963046,7/31/2025 10:55:00 PM,RTD,7/31/2025 11:00:00 PM,CMIN,14TIN_T1L2,NL,-101.26,15075.6122,0.8451,12741.3896,2334.2226,0.0,NaN
9963047,EOF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Fill missing RUN_TIME values with TIME_INTERVAL if RUN_TIME is NaN and TIME_INTERVAL is valid
july2025_mw['RUN_TIME'] = pd.to_datetime(july2025_mw['RUN_TIME'], errors='coerce')
july2025_mw['TIME_INTERVAL'] = pd.to_datetime(july2025_mw['TIME_INTERVAL'], errors='coerce')

# If RUN_TIME is NaN but TIME_INTERVAL is valid, use TIME_INTERVAL's date and set time to 00:00
mask = july2025_mw['RUN_TIME'].isna() & july2025_mw['TIME_INTERVAL'].notna()
july2025_mw.loc[mask, 'RUN_TIME'] = july2025_mw.loc[mask, 'TIME_INTERVAL'].dt.normalize()

# Format as 'YYYY-MM-DD HH:MM'
july2025_mw['RUN_TIME'] = july2025_mw['RUN_TIME'].dt.strftime('%Y-%m-%d %H:%M')
july2025_mw['TIME_INTERVAL'] = july2025_mw['TIME_INTERVAL'].dt.strftime('%Y-%m-%d %H:%M')

C:\Users\theam\AppData\Local\Temp\ipykernel_16924\2154836548.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  july2025_mw['RUN_TIME'] = pd.to_datetime(july2025_mw['RUN_TIME'], errors='coerce')
C:\Users\theam\AppData\Local\Temp\ipykernel_16924\2154836548.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  july2025_mw['TIME_INTERVAL'] = pd.to_datetime(july2025_mw['TIME_INTERVAL'], errors='coerce')

In [6]:
# Convert RUN_TIME and TIME_INTERVAL in july2025_mp to military time (24-hour format)
# If RUN_TIME is just a date (e.g. '7/16/2025'), set it to '00:00' for that day
def fix_run_time(val, prev_time=None):
    try:
        dt = pd.to_datetime(val, errors='coerce')
        if pd.isnull(dt):
            return np.nan
        # If original string has no time, set to 00:00
        if len(str(val).strip()) <= 10:
            return dt.strftime('%Y-%m-%d 00:00')
        else:
            return dt.strftime('%Y-%m-%d %H:%M')
    except:
        return np.nan

july2025_mp['RUN_TIME'] = [fix_run_time(val) for val in july2025_mp['RUN_TIME']]
july2025_mp['TIME_INTERVAL'] = pd.to_datetime(july2025_mp['TIME_INTERVAL'], errors='coerce').dt.strftime('%Y-%m-%d %H:%M')

# Display to verify conversion
print(july2025_mp[['RUN_TIME', 'TIME_INTERVAL']].head())

C:\Users\theam\AppData\Local\Temp\ipykernel_16924\1276011773.py:17: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  july2025_mp['TIME_INTERVAL'] = pd.to_datetime(july2025_mp['TIME_INTERVAL'], errors='coerce').dt.strftime('%Y-%m-%d %H:%M')

           RUN_TIME     TIME_INTERVAL
0  2025-07-01 00:00  2025-07-01 00:05
1  2025-07-01 00:00  2025-07-01 00:05
2  2025-07-01 00:05  2025-07-01 00:10
3  2025-07-01 00:05  2025-07-01 00:10
4  2025-07-01 00:05  2025-07-01 00:10

In [7]:
display(july2025_mp)
display(july2025_mw)

,RUN_TIME,MKT_TYPE,TIME_INTERVAL,REGION_NAME,RESOURCE_NAME,RESOURCE_TYPE,COMMODITY_TYPE,MARGINAL_PRICE,Unnamed: 8
0,2025-07-01 00:00,RTD,2025-07-01 00:05,CLUZ,03STA-RI_G01,G,En,5412.20,NaN
1,2025-07-01 00:00,RTD,2025-07-01 00:05,CMIN,14SARANG_U02,G,En,2731.00,NaN
2,2025-07-01 00:05,RTD,2025-07-01 00:10,CLUZ,03PAGBIL_G01,G,En,3536.43,NaN
3,2025-07-01 00:05,RTD,2025-07-01 00:10,CLUZ,03PAGBIL_G02,G,En,3536.43,NaN
4,2025-07-01 00:05,RTD,2025-07-01 00:10,CMIN,14SARANG_U02,G,En,2731.00,NaN
...,...,...,...,...,...,...,...,...,...
20708,2025-07-31 23:55,RTD,2025-08-01 00:00,CMIN,10GNPK_U01,G,En,5400.00,NaN
20709,2025-07-31 23:55,RTD,2025-08-01 00:00,CMIN,10GNPK_U02,G,En,5400.00,NaN
20710,2025-07-31 23:55,RTD,2025-08-01 00:00,CMIN,10GNPK_U03,G,En,5400.00,NaN
20711,2025-07-31 23:55,RTD,2025-08-01 00:00,CMIN,10GNPK_U04,G,En,5400.00,NaN
20712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,RUN_TIME,MKT_TYPE,TIME_INTERVAL,REGION_NAME,RESOURCE_NAME,RESOURCE_TYPE,SCHED_MW,LMP,LOSS_FACTOR,LMP_SMP,LMP_LOSS,LMP_CONGESTION,Unnamed: 12
0,2025-06-30 23:00,RTD,2025-06-30 23:05,CLUZ,01ACNPC_G01,G,1.00,3398.8958,0.9793,3328.6611,70.2347,0.0,NaN
1,2025-06-30 23:00,RTD,2025-06-30 23:05,CLUZ,01AEC_L01,NL,-49.70,3396.8986,0.9799,3328.6611,68.2376,0.0,NaN
2,2025-06-30 23:00,RTD,2025-06-30 23:05,CLUZ,01AMBUK_SS,NL,0.00,3379.9225,0.9848,3328.6611,51.2614,0.0,NaN
3,2025-06-30 23:00,RTD,2025-06-30 23:05,CLUZ,01AMBUK_T1L1,NL,0.00,3379.9225,0.9848,3328.6611,51.2614,0.0,NaN
4,2025-06-30 23:00,RTD,2025-06-30 23:05,CLUZ,01AMBUK_U01,G,37.50,3377.9253,0.9854,3328.6611,49.2642,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9963043,2025-07-31 22:55,RTD,2025-07-31 23:00,CMIN,14TACSUR_L02,NL,-29.15,15465.4987,0.8239,12741.3896,2724.1091,0.0,NaN
9963044,2025-07-31 22:55,RTD,2025-07-31 23:00,CMIN,14TACUR_SS,NL,0.00,15459.1280,0.8242,12741.3896,2717.7384,0.0,NaN
9963045,2025-07-31 22:55,RTD,2025-07-31 23:00,CMIN,14TIN_T1L1,NL,-19.33,15075.6122,0.8451,12741.3896,2334.2226,0.0,NaN
9963046,2025-07-31 22:55,RTD,2025-07-31 23:00,CMIN,14TIN_T1L2,NL,-101.26,15075.6122,0.8451,12741.3896,2334.2226,0.0,NaN
9963047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Merge july2025_mw and july2025_mp on RUN_TIME, TIME_INTERVAL, and REGION_NAME, adding MARGINAL_PRICE from july2025_mp
july2025_combined = pd.merge(
    july2025_mw,
    july2025_mp[['RUN_TIME','TIME_INTERVAL','REGION_NAME','MARGINAL_PRICE']],
    on=['RUN_TIME','TIME_INTERVAL','REGION_NAME'],
    how='left',
    suffixes=('', '_mp')
)
display(july2025_combined)

,RUN_TIME,MKT_TYPE,TIME_INTERVAL,REGION_NAME,RESOURCE_NAME,RESOURCE_TYPE,SCHED_MW,LMP,LOSS_FACTOR,LMP_SMP,LMP_LOSS,LMP_CONGESTION,Unnamed: 12,MARGINAL_PRICE
0,2025-06-30 23:00,RTD,2025-06-30 23:05,CLUZ,01ACNPC_G01,G,1.0,3398.8958,0.9793,3328.6611,70.2347,0.0,NaN,NaN
1,2025-06-30 23:00,RTD,2025-06-30 23:05,CLUZ,01AEC_L01,NL,-49.7,3396.8986,0.9799,3328.6611,68.2376,0.0,NaN,NaN
2,2025-06-30 23:00,RTD,2025-06-30 23:05,CLUZ,01AMBUK_SS,NL,0.0,3379.9225,0.9848,3328.6611,51.2614,0.0,NaN,NaN
3,2025-06-30 23:00,RTD,2025-06-30 23:05,CLUZ,01AMBUK_T1L1,NL,0.0,3379.9225,0.9848,3328.6611,51.2614,0.0,NaN,NaN
4,2025-06-30 23:00,RTD,2025-06-30 23:05,CLUZ,01AMBUK_U01,G,37.5,3377.9253,0.9854,3328.6611,49.2642,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13379287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13379288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13379289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13379290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13379291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Clean the merged DataFrame
import pandas as pd
from datetime import datetime
# Drop columns with all missing values
july2025_combined = july2025_combined.dropna(axis=1, how='all')
# Convert RUN_TIME to datetime for filtering
july2025_combined['RUN_TIME'] = pd.to_datetime(july2025_combined['RUN_TIME'], errors='coerce')
# Filter for dates from July 1, 2025 onwards
july2025_combined = july2025_combined[july2025_combined['RUN_TIME'] >= datetime(2025, 7, 1)]
# Remove rows with missing RUN_TIME (if any remain)
july2025_combined = july2025_combined[july2025_combined['RUN_TIME'].notna()]
# Display cleaned DataFrame
display(july2025_combined)

C:\Users\theam\AppData\Local\Temp\ipykernel_16924\865496306.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  july2025_combined['RUN_TIME'] = pd.to_datetime(july2025_combined['RUN_TIME'], errors='coerce')

,RUN_TIME,MKT_TYPE,TIME_INTERVAL,REGION_NAME,RESOURCE_NAME,RESOURCE_TYPE,SCHED_MW,LMP,LOSS_FACTOR,LMP_SMP,LMP_LOSS,LMP_CONGESTION,MARGINAL_PRICE
13351,2025-07-01 00:00:00,RTD,2025-07-01 00:05,CLUZ,01ACNPC_G01,G,1.00,5792.6700,0.9789,5670.1938,122.4762,0.0,5412.2
13352,2025-07-01 00:00:00,RTD,2025-07-01 00:05,CLUZ,01AEC_L01,NL,-46.72,5790.4019,0.9793,5670.1938,120.2081,0.0,5412.2
13353,2025-07-01 00:00:00,RTD,2025-07-01 00:05,CLUZ,01AMBUK_SS,NL,0.00,5727.4628,0.9900,5670.1938,57.2690,0.0,5412.2
13354,2025-07-01 00:00:00,RTD,2025-07-01 00:05,CLUZ,01AMBUK_T1L1,NL,0.00,5727.4628,0.9900,5670.1938,57.2690,0.0,5412.2
13355,2025-07-01 00:00:00,RTD,2025-07-01 00:05,CLUZ,01AMBUK_U01,G,37.50,5724.6277,0.9905,5670.1938,54.4339,0.0,5412.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13379256,2025-07-31 22:55:00,RTD,2025-07-31 23:00,CMIN,14SUPKOR_G01,G,0.00,15484.6108,0.8229,12741.3896,2743.2212,0.0,12800.0
13379257,2025-07-31 22:55:00,RTD,2025-07-31 23:00,CMIN,14TACSUR_L02,NL,-29.15,15465.4987,0.8239,12741.3896,2724.1091,0.0,12800.0
13379258,2025-07-31 22:55:00,RTD,2025-07-31 23:00,CMIN,14TACUR_SS,NL,0.00,15459.1280,0.8242,12741.3896,2717.7384,0.0,12800.0
13379259,2025-07-31 22:55:00,RTD,2025-07-31 23:00,CMIN,14TIN_T1L1,NL,-19.33,15075.6122,0.8451,12741.3896,2334.2226,0.0,12800.0
13379260,2025-07-31 22:55:00,RTD,2025-07-31 23:00,CMIN,14TIN_T1L2,NL,-101.26,15075.6122,0.8451,12741.3896,2334.2226,0.0,12800.0

In [10]:
july2025_filtered = july2025_combined[july2025_combined['SCHED_MW'] > 0]
display(july2025_filtered)

,RUN_TIME,MKT_TYPE,TIME_INTERVAL,REGION_NAME,RESOURCE_NAME,RESOURCE_TYPE,SCHED_MW,LMP,LOSS_FACTOR,LMP_SMP,LMP_LOSS,LMP_CONGESTION,MARGINAL_PRICE
13351,2025-07-01 00:00:00,RTD,2025-07-01 00:05,CLUZ,01ACNPC_G01,G,1.0,5792.6700,0.9789,5670.1938,122.4762,0.0,5412.2
13355,2025-07-01 00:00:00,RTD,2025-07-01 00:05,CLUZ,01AMBUK_U01,G,37.5,5724.6277,0.9905,5670.1938,54.4339,0.0,5412.2
13356,2025-07-01 00:00:00,RTD,2025-07-01 00:05,CLUZ,01AMBUK_U02,G,37.5,5724.6277,0.9905,5670.1938,54.4339,0.0,5412.2
13358,2025-07-01 00:00:00,RTD,2025-07-01 00:05,CLUZ,01AMPHAW_G01,G,9.5,5726.3287,0.9902,5670.1938,56.1349,0.0,5412.2
13359,2025-07-01 00:00:00,RTD,2025-07-01 00:05,CLUZ,01ANDA_G01,G,40.5,5790.4019,0.9793,5670.1938,120.2081,0.0,5412.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13379242,2025-07-31 22:55:00,RTD,2025-07-31 23:00,CMIN,14MTAPO_U01,G,44.0,14241.0512,0.8947,12741.3896,1499.6616,0.0,12800.0
13379243,2025-07-31 22:55:00,RTD,2025-07-31 23:00,CMIN,14MTAPO_U02,G,33.0,14246.1477,0.8944,12741.3896,1504.7581,0.0,12800.0
13379244,2025-07-31 22:55:00,RTD,2025-07-31 23:00,CMIN,14MTAPO_U03,G,3.6,14283.0978,0.8921,12741.3896,1541.7081,0.0,12800.0
13379248,2025-07-31 22:55:00,RTD,2025-07-31 23:00,CMIN,14SARANG_U01,G,122.0,15075.6122,0.8451,12741.3896,2334.2226,0.0,12800.0
13379250,2025-07-31 22:55:00,RTD,2025-07-31 23:00,CMIN,14SIGHYDRO_G01,G,10.9,15075.6122,0.8451,12741.3896,2334.2226,0.0,12800.0

In [11]:
# Count missing values in MARGINAL_PRICE column of july2025_filtered
missing_marginal_price_count = july2025_filtered['MARGINAL_PRICE'].isna().sum()
print(f"Number of missing observations in MARGINAL_PRICE: {missing_marginal_price_count}")

Number of missing observations in MARGINAL_PRICE: 1012433